---
- hosts: windows
  tasks:
    - name: ensure docker-desktop is installed
      win_chocolatey:
        name: docker-desktop
        state: latest
    - name: ensure clion is installed
      win_chocolatey:
        name: clion-ide
        state: latest
    - name: ensure goland is installed
      win_chocolatey:
        name: goland
        state: latest
    - name: ensure datagrip is installed
      win_chocolatey:
        name: datagrip
        state: latest
    - name: ensure vscode is installed
      win_chocolatey:
        name: vscode
        state: latest
    - name: ensure wireshark is installed
      win_chocolatey:
        name: wireshark
        state: latest
    - name: ensure slack is installed
      win_chocolatey:
        name: slack
        state: latest 
    - name: ensure vagrant 2.2.4 is installed
      win_chocolatey:
        name: vagrant
        state: present
        version: 2.2.4
