---
postgres_repo: https://github.com/postgres/postgres
# postgres_version: < if set, check out this version >

_checkout_postgres: False

build_core_count: "{{ ansible_facts['processor_vcpus'] }}"

build_postgres_default_config:
    repo: "{{ postgres_repo }}"
    repo_directory: "{{ansible_env.HOME}}/workspace/postgres"
    repo_version: HEAD
    repo_force: False
    repo_update: False

    # Build flags
    with_lz4: False
    enable_debug: True
    enable_cassert: True
    cflags: "-O0 -fno-omit-frame-pointer"

    prefix: "/usr/local/pgsql"

    build_core_count: "{{ build_core_count }}"
