---
- name: Build gpdb
  hosts: localhost
  vars:
    greenplum_config: {}
    orca_config: {}
    xerces_config: {}
  vars_files:
    - "{{userconfig}}"
  gather_facts: yes

  roles:
    - build_gpdb
