---
- name: setup a Linux environment
  hosts: localhost
  gather_facts: yes
  vars:
    is_wsl: False
    is_vagrant: False
  vars_files:
    - "{{userconfig}}"

  pre_tasks:
    - name: mandatory variables
      assert:
        that:
          - git_user is defined
          - git_email is defined

  roles:
    - common
    - dev_tools

- import_playbook: windows.yaml
  when: is_wsl == True
