---
- name: setup a Linux environment
  hosts: localhost
  gather_facts: yes
  vars:
    is_wsl: False
    is_vagrant: False
  vars_files:
    - "{{userconfig}}"
  tags:
    - linux

  pre_tasks:
    - include: set_windows_vars.yaml
    - name: mandatory variables
      assert:
        that:
          - git_user is defined
          - git_email is defined
  roles:
    - common
    - dev_tools
    - kube_dev
    - postgres_dev
    - yugabyte_dev

- import_playbook: build_gpdb.yaml
  tags:
    - build_gpdb
  when:
   - build_gpdb is defined
   - build_gpdb | bool

- import_playbook: build_postgres.yaml
  tags:
    - build_postgres
  when:
   - build_postgres is defined
   - build_postgres | bool

- import_playbook: windows.yaml
  tags:
    - windows
