---
- name: Add Windows host
  hosts: localhost
  gather_facts: yes
  pre_tasks:
    - include: set_windows_vars.yaml
    - add_host:
        name: windows.localhost
        groups: [windows]
        ansible_host: "{{ host_address }}"
        ansible_connection: winrm
        ansible_winrm_cert_pem: /etc/ansible/certificates/WinRMCert.pem
        ansible_winrm_cert_key_pem: /etc/ansible/certificates/cert_key.pem
        ansible_winrm_transport: certificate
        ansible_winrm_server_cert_validation: ignore
      when:
        - is_wsl

- name: Check defaults
  hosts: windows
  gather_facts: yes
  vars_files:
    - "{{userconfig}}"

  roles:
    - windows_common
    - windows_dev_tools
