---
- name: Add Windows host
  hosts: localhost
  gather_facts: yes
  pre_tasks:
    - set_fact:
        is_wsl1: "{{ ansible_facts['kernel'] is match('.*Microsoft.*') }}"
        is_wsl2: "{{ ansible_facts['kernel'] is match('.*microsoft.*') }}"
    - shell: "tail -1 /etc/resolv.conf | cut -d' ' -f2"
      when: is_wsl2
      register: cmd
    - set_fact:
        is_wsl: "{{ is_wsl1 or is_wsl2 }}"
        host_address: "{{ is_wsl2 | ternary(cmd.stdout, '127.0.0.1') }}"
    - add_host:
        name: windows.localhost
        groups: [windows]
        ansible_host: "{{ host_address }}"
        ansible_connection: winrm
        ansible_winrm_cert_pem: /etc/ansible/certificates/WinRMCert.pem
        ansible_winrm_cert_key_pem: /etc/ansible/certificates/cert_key.pem
        ansible_winrm_transport: certificate
        ansible_winrm_server_cert_validation: ignore
      when:
        - is_wsl

- name: Check defaults
  hosts: windows
  gather_facts: yes
  vars_files:
    - "{{userconfig}}"

  pre_tasks:
    - name: mandatory variables
      assert:
        that:
          - is_wsl == True

  roles:
    - windows_common
    - windows_dev_tools
