---
- name: Check defaults
  hosts: windows
  gather_facts: yes
  vars:
    is_wsl: False
    is_vagrant: False
  vars_files:
    - "{{userconfig}}"

  pre_tasks:
    - name: mandatory variables
      assert:
        that:
          - is_wsl == True

  roles:
    - windows_common
    - windows_dev_tools
