---
- name: Download kubebuilder to /tmp/
  get_url:
    url: https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.1.0/kubebuilder_2.1.0_linux_amd64.tar.gz
    dest: /tmp/kubebuilder_2.1.0_linux_amd64.tar.gz
- name: Extract kubebuilder
  unarchive:
    remote_src: yes
    src: /tmp/kubebuilder_2.1.0_linux_amd64.tar.gz
    dest: /usr/local/
  become: yes
- name: Set kubebuilder 2.1.0 as the system default
  file:
    src: /usr/local/kubebuilder_2.1.0_linux_amd64
    dest: /usr/local/kubebuilder
    state: link
    mode: 0755
  become: yes
