---
- include: packages_ubuntu1804.yaml
  become: yes
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "18.04"
- include: bashrc.yaml
- include: helm.yaml
- include: kubebuilder.yaml
- include: kustomize.yaml
#- include: minikube.yaml
