---
- name: Create the workspace directory
  file:
    path: "{{ ansible_env.HOME }}/workspace"
    state: directory
    mode: 0755
- name: Cloning yugabyte-db into ~/workspace
  git:
    repo: "https://github.com/yugabyte/yugabyte-db"
    dest: "{{ ansible_env.HOME }}/workspace/yugabyte-db"
    remote: origin
    update: no
