---
- name: Create the deployments directory
  file:
    path: "{{ ansible_env.HOME }}/deployments"
    state: directory
    mode: 0755
- name: Create the workspace directory
  file:
    path: "{{ ansible_env.HOME }}/workspace"
    state: directory
- name: Cloning gpdb into ~/workspace
  git:
    repo: "https://github.com/greenplum-db/gpdb"
    dest: "{{ ansible_env.HOME }}/workspace/gpdb"
    remote: origin
    update: no
# Allows CLion to intraspect the gpdb project
- name: Add a CMakeLists.txt file to the gpdb repo
  copy:
    src: CMakeLists.gpdb
    dest: "{{ansible_env.HOME}}/workspace/gpdb/CMakeLists.txt"
    mode: 0644
- name: Cloning gdbpg into ~/workspace
  git:
    repo: "https://github.com/tvesely/gdbpg"
    dest: "{{ ansible_env.HOME }}/workspace/gdbpg"
    remote: origin
- name: Cloning gphelpers into ~/workspace
  git:
    repo: "https://github.com/tvesely/gphelpers"
    dest: "{{ ansible_env.HOME }}/workspace/gphelpers"
    remote: origin
- name: Cloning gp-xerces into ~/workspace
  git:
    repo: "https://github.com/greenplum-db/gp-xerces"
    dest: "{{ ansible_env.HOME }}/workspace/gp-xerces"
    remote: origin
- name: Cloning gporca into ~/workspace
  git:
    repo: "https://github.com/greenplum-db/gporca"
    dest: "{{ ansible_env.HOME }}/workspace/gporca"
    remote: origin
    update: no
- name: Cloning postgres into ~/workspace
  git:
    repo: "https://github.com/postgres/postgres"
    dest: "{{ ansible_env.HOME }}/workspace/postgres"
    remote: origin
    update: no
  tags:
    -postgres
# Allows CLion to intraspect the postgres project
- name: Add a CMakeLists.txt file to the postgres repo
  copy:
    src: CMakeLists.postgres
    dest: "{{ansible_env.HOME}}/workspace/postgres/CMakeLists.txt"
    mode: 0644
  tags:
    -postgres
- name: Cloning tpch-dbgen into ~/workspace
  git:
    repo: "https://github.com/electrum/tpch-dbgen"
    dest: "{{ ansible_env.HOME }}/workspace/tpch-dbgen"
    remote: origin
  tags:
      - tpch-dbgen
- name: Build and install tpch-dbgen
  command: "make -j{{ansible_facts['processor_vcpus']}}"
  args:
    chdir: "{{ ansible_env.HOME }}/workspace/tpch-dbgen"
  tags:
      - tpch-dbgen
- name: Run tpch data generation
  command: "./dbgen -T L -s {{tpch_datagen_scale}} -f"
  args:
    chdir: "{{ ansible_env.HOME }}/workspace/tpch-dbgen"
  tags:
      - tpch-dbgen
  when:
    - run_tpch_datagen == True
- name: Cloning pg_bsd_indent into ~/workspace
  git:
    repo: "https://git.postgresql.org/git/pg_bsd_indent"
    dest: "{{ ansible_env.HOME }}/workspace/pg_bsd_indent"
    remote: origin
  tags:
    - pg_indent
