---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
- name: Add user
  user:
    name: "{{ansible_env.USER }}"
    shell: /bin/bash
    groups: wheel,docker
    append: yes
- name: Make /usr/local/lib/ group wheel
  file:
    path: "/usr/local/lib"
    state: directory
    mode: 0775
    owner: root
    group: wheel
- name: Make /usr/local/include/ group wheel
  file:
    path: "/usr/local/include"
    state: directory
    mode: 0775
    owner: root
    group: wheel
- name: Create a directory for gpdb installation
  file:
    path: "/usr/local/gpdb"
    state: directory
    mode: 0755
    owner: "{{ansible_env.USER }}"
    group: "{{ansible_env.USER }}"
- name: Create a directory for postgres installation
  file:
    path: "/usr/local/pgsql"
    state: directory
    mode: 0755
    owner: "{{ansible_env.USER }}"
    group: "{{ansible_env.USER }}"
