- name: Create the CLion2019.1 directory
  file:
    path: "{{ ansible_env.HOME }}/.CLion2019.1/"
    state: directory
    mode: 0755
- name: Create the CLion2019.1/config directory
  file:
    path: "{{ ansible_env.HOME }}/.CLion2019.1/config"
    state: directory
    mode: 0755
- name: Add default CLion vmoptions
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.CLion2019.1/config/clion64.vmoptions"
    block: "{{ lookup('file', '~/deployments/envsetup/roles/dev_tools/files/clion64.vmoptions.defaults') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK CLION COMMON"
    create: yes
- name: Add X11 forwarding Clion vmoptions
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.CLion2019.1/config/clion64.vmoptions"
    block: "{{ lookup('file', '~/deployments/envsetup/roles/dev_tools/files/clion64.vmoptions.x11') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK X11 FORWARDING COMMON"
    create: yes
