- name: Install docker
  apt:
    name: "docker.io"
    state: present
- name: Install vagrant 2.2.6
  apt:
    deb: https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb
    state: present
  when: is_vagrant == False
  tags:
    - vagrant
# Requirements for go development
- name: Apt install the go programming language package
  apt:
    name: "golang-go"
    state: present
  when: is_wsl == True
- name: Snap install the go programming language package
  snap:
    name: "go"
    state: present
    classic: yes
    channel: 1.14/stable
  when: is_wsl == False
- name: Install the direnv package
  apt:
    name: direnv
    state: present
  tags:
    - direnv

# Development utilities
- name: Install valgrind
  apt:
    name: "valgrind"
    state: present

# Snap installs aren't available on WSL (yet)
- name: Install the clion package
  snap:
    name: "clion"
    state: present
    classic: yes
  when: is_wsl == False
- name: Install the goland package
  snap:
    name: "goland"
    state: present
    classic: yes
  when: is_wsl == False
- name: Install fontconfig for fonts in x11 for clion
  apt:
    name: "fontconfig"
    state: present
  when: is_wsl == False
- name: Install the gcloud package
  snap:
    name: "google-cloud-sdk"
    state: present
    classic: yes
  when: is_wsl == False
