- name: Install docker
  apt:
    name: "docker.io"
    state: present
- name: Install vagrant 2.2.5
  apt:
    deb: https://releases.hashicorp.com/vagrant/2.2.5/vagrant_2.2.5_x86_64.deb
    state: present
  when: is_vagrant == False
  tags:
    - vagrant
# Requirements for go development
- name: Install the go programming language package
  apt:
    name: "golang-go"
    state: present

# Snap installs aren't available on WSL (yet)
- name: Install the clion package
  snap:
    name: "clion"
    state: present
    classic: yes
  when: is_wsl == False
- name: Install fontconfig for fonts in x11 for clion
  apt:
    name: "fontconfig"
    state: present
  when: is_wsl == False
