---
- name: Download and install pivnet-cli 0.0.57
  get_url:
    url: https://github.com/pivotal-cf/pivnet-cli/releases/download/v0.0.57/pivnet-linux-amd64-0.0.57
    dest: /usr/local/bin/pivnet-linux-amd64-0.0.57
    mode: 0755
  become: yes
- name: Set pivnet-cli 0.0.57 as the system default
  file:
    src: /usr/local/bin/pivnet-linux-amd64-0.0.57
    dest: /usr/local/bin/pivnet
    state: link
    mode: 0755
  become: yes
