- hosts: localhost
  vars_files:
    - '{{userconfig}}'
  tasks:
  - name: Create the CLion2019.1 directory
    file:
      path: "{{ lookup('env','HOME') }}/.CLion2019.1/"
      state: directory
      mode: 0755
      owner: "{{lookup ('env', 'USER') }}"
      group: "{{lookup ('env', 'USER') }}"
  - name: Create the CLion2019.1/config directory
    file:
      path: "{{ lookup('env','HOME') }}/.CLion2019.1/config"
      state: directory
      mode: 0755
      owner: "{{lookup ('env', 'USER') }}"
      group: "{{lookup ('env', 'USER') }}"
  - name: Add default CLion vmoptions
    blockinfile:
      dest: "{{ lookup('env','HOME') }}/.CLion2019.1/config/clion64.vmoptions"
      block: "{{ lookup('file', '~/deployments/envsetup/clion/clion64.vmoptions.defaults') }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK CLION COMMON"
      create: yes
  - name: Add X11 forwarding Clion vmoptions
    blockinfile:
      dest: "{{ lookup('env','HOME') }}/.CLion2019.1/config/clion64.vmoptions"
      block: "{{ lookup('file', '~/deployments/envsetup/clion/clion64.vmoptions.x11') }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK X11 FORWARDING COMMON"
      create: yes
    when: is_wsl == True or is_vagrant == True
