---
- hosts: localhost
  tasks:
    - name: Create the build directory
      file:
        path: "{{ lookup('env','HOME') }}/build"
        state: directory
        mode: 0755
        owner: "{{lookup ('env', 'USER') }}"
        group: "{{lookup ('env', 'USER') }}"
    - name: Create the golang directory
      file:
        path: "{{ lookup('env','HOME') }}/build/golang"
        state: directory
        mode: 0755
        owner: "{{lookup ('env', 'USER') }}"
        group: "{{lookup ('env', 'USER') }}"
