---
- hosts: localhost
  tasks:
    - name: Create the nes directory
      file:
        path: "{{ lookup('env','HOME') }}/build/nes"
        state: directory
        mode: 0755
        owner: "{{lookup ('env', 'USER') }}"
        group: "{{lookup ('env', 'USER') }}"
    - name: Create the tools directory
      file:
        path: "{{ lookup('env','HOME') }}/build/nes/tools"
        state: directory
        mode: 0755
        owner: "{{lookup ('env', 'USER') }}"
        group: "{{lookup ('env', 'USER') }}"

    - name: Cloning cc65 into ~/build/nes/tools
      git:
        repo: "https://github.com/cc65/cc65.git"
        dest: "{{ lookup('env','HOME') }}/build/nes/tools/cc65"
        remote: origin
        update: no
    - name: Cloning ld65-labels into ~/build/nes/tools
      git:
        repo: "https://github.com/zorchenhimer/ld65-labels.git"
        dest: "{{ lookup('env','HOME') }}/build/nes/tools/ld65-labels"
        remote: origin
        update: no
    - name: Cloning nes-runner into ~/build/nes
      git:
        repo: "https://github.com/zorchenhimer/nes-runner"
        dest: "{{ lookup('env','HOME') }}/build/nes/nes-runner"
        remote: origin
        update: no
    - name: Build cc65
      command: "make -j8"
      args:
        chdir: "{{ lookup('env','HOME') }}/build/nes/tools/cc65"
        creates: "{{ lookup('env','HOME') }}/build/nes/tools/cc65/bin/cc65"
    - name: Build ld65-labels
      command: go build
      args:
        chdir: "{{ lookup('env','HOME') }}/build/nes/tools/ld65-labels"
        creates: "{{ lookup('env','HOME') }}/build/nes/tools/ld65-labels/ld65-labels"
