---
- hosts: localhost
  tasks:
    - name: Create the deployments directory
      file:
        path: "{{ lookup('env','HOME') }}/deployments"
        state: directory
        mode: 0755
    - name: Create the workspace directory
      file:
        path: "{{ lookup('env','HOME') }}/workspace"
        state: directory
    - name: Cloning gpdb into ~/workspace
      git:
        repo: "https://github.com/greenplum-db/gpdb"
        dest: "{{ lookup('env','HOME') }}/workspace/gpdb"
        remote: origin
        update: no
    - git_config:
        name: user.email
        repo: "{{ lookup('env','HOME') }}/workspace/gpdb"
        scope: local
        value: 'tvesely@pivotal.io'
    # Allows CLion to intraspect the gpdb project
    - name: Add a CMakeLists.txt file to the gpdb repo
      copy:
        src: "{{lookup ('env', 'HOME')}}/deployments/envsetup/gpdb/CMakeLists.txt"
        dest: "{{lookup ('env', 'HOME')}}/workspace/gpdb/CMakeLists.txt"
        mode: 0644
        owner: "{{lookup ('env', 'USER') }}"
        group: "{{lookup ('env', 'USER') }}"
    - name: Cloning gdbpg into ~/workspace
      git:
        repo: "https://github.com/tvesely/gdbpg"
        dest: "{{ lookup('env','HOME') }}/workspace/gdbpg"
        remote: origin
    - git_config:
        name: user.email
        repo: "{{ lookup('env','HOME') }}/workspace/gdbpg"
        scope: local
        value: 'tvesely@pivotal.io'
    - name: Cloning gphelpers into ~/workspace
      git:
        repo: "https://github.com/tvesely/gphelpers"
        dest: "{{ lookup('env','HOME') }}/workspace/gphelpers"
        remote: origin
    - git_config:
        name: user.email
        repo: "{{ lookup('env','HOME') }}/workspace/gphelpers"
        scope: local
        value: 'tvesely@pivotal.io'
    - name: Cloning gp-xerces into ~/workspace
      git:
        repo: "https://github.com/greenplum-db/gp-xerces"
        dest: "{{ lookup('env','HOME') }}/workspace/gp-xerces"
        remote: origin
    - name: Create gp-xerces build directory
      file:
        path: "{{ lookup('env','HOME') }}/workspace/gp-xerces/build"
        state: directory
        mode: 0755
    - name: Configure gp-xerces
      command: "./configure --prefix=/usr/local"
      args:
        chdir: "{{ lookup('env','HOME') }}/workspace/gp-xerces/build"
        creates: "{{ lookup('env','HOME') }}/workspace/gp-xerces/build/Makefile"
    - name: Build gp-xerces
      command: "make -j8"
      args:
        chdir: "{{ lookup('env','HOME') }}/workspace/gp-xerces/build"
    - name: Install gp-xerces
      command: "make install"
      args:
        chdir: "{{ lookup('env','HOME') }}/workspace/gp-xerces/build"
        creates: "/usr/local/lib/libxerces-c-3.1.so"
      become: yes
    - name: Cloning gporca into ~/workspace
      git:
        repo: "https://github.com/greenplum-db/gporca"
        dest: "{{ lookup('env','HOME') }}/workspace/gporca"
        remote: origin
    - git_config:
        name: user.email
        repo: "{{ lookup('env','HOME') }}/workspace/gporca"
        scope: local
        value: 'tvesely@pivotal.io'
    - name: Cloning postgres into ~/workspace
      git:
        repo: "https://github.com/postgres/postgres"
        dest: "{{ lookup('env','HOME') }}/workspace/postgres"
        remote: origin
    # Allows CLion to intraspect the postgres project
    - name: Add a CMakeLists.txt file to the postgres repo
      copy:
        src: "{{lookup ('env', 'HOME')}}/deployments/envsetup/postgres/CMakeLists.txt"
        dest: "{{lookup ('env', 'HOME')}}/workspace/postgres/CMakeLists.txt"
        mode: 0644
        owner: "{{lookup ('env', 'USER') }}"
        group: "{{lookup ('env', 'USER') }}"
    # Developer tools go here
    - name: Cloning bpftrace into ~/build
      git:
        repo: "https://github.com/iovisor/bpftrace"
        dest: "{{ lookup('env','HOME') }}/build/bpftrace"
        remote: origin
    - name: Cloning bcc into ~/build
      git:
        repo: "https://github.com/iovisor/bcc"
        dest: "{{ lookup('env','HOME') }}/build/bcc"
        remote: origin
