---
- hosts: localhost 
  become: yes
  tasks:
  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present
  
  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add user
    user:
      name: "{{lookup ('env', 'USER') }}"
      shell: /bin/bash
      groups: wheel,docker
      append: yes
