---
- name: ensure 7-Zip is installed
  win_chocolatey:
    name: 7zip
    state: latest
- name: ensure Firefox is installed
  win_chocolatey:
    name: firefox
    state: latest
- name: ensure notepad++ is installed
  win_chocolatey:
    name: notepadplusplus
    state: latest
- name: ensure sysinternals is installed
  win_chocolatey:
    name: sysinternals
    state: latest
- name: ensure process explorer is installed
  win_chocolatey:
    name: procexp
    state: latest
- name: ensure steam is installed
  win_chocolatey:
    name: steam
    state: latest
- name: ensure java runtime is installed
  win_chocolatey:
    name: javaruntime
    state: latest
- name: ensure vlc is installed
  win_chocolatey:
    name: vlc
    state: latest
- name: ensure procmon is installed
  win_chocolatey:
    name: procmon
    state: latest
- name: ensure discord is installed
  win_chocolatey:
    name: discord
    state: latest
- name: ensure keybase is installed
  win_chocolatey:
    name: keybase
    state: latest
