---
- name: Install Powershell Profile
  win_copy:
    src: Microsoft.PowerShell_profile.ps1
    dest: "{{ ansible_facts['env']['USERPROFILE'] }}/Documents/WindowsPowerShell/Microsoft.Powershell_profile.ps1"
  register: result
- name: Sign Powershell Profile with Code Signing Certificate
  win_shell: |
      $cert = Get-PfxCertificate -FilePath {{ ansible_facts['env']['USERPROFILE'] }}/deployments/windeploy/ansible/certificates/CodeSigningCert.pfx
      Set-AuthenticodeSignature -FilePath {{ ansible_facts['env']['USERPROFILE'] }}/Documents/WindowsPowerShell/Microsoft.Powershell_profile.ps1 `
        -Certificate $cert
  when: result.changed
