- name: Add common bashrc customizations
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    block: "{{ lookup('file', '~/deployments/envsetup/roles/common/files/bashrc.common') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK BASHRC COMMON"
    create: yes
