---
- name: Install the .tmux.conf to the user's home folder
  copy:
    src: "{{lookup ('env', 'HOME')}}/deployments/envsetup/roles/common/files/tmux.conf"
    dest: "{{ansible_env.HOME}}/.tmux.conf"
    mode: 0755
    owner: "{{ansible_env.USER }}"
    group: "{{ansible_env.USER }}"
