---
- name: Create the vim directory
  file:
    path: "{{ ansible_env.HOME }}/.vim"
    state: directory
    mode: 0755
- name: Create the autoload directory
  file:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
    state: directory
    mode: 0755
- name: Create the bundle directory
  file:
    path: "{{ ansible_env.HOME }}/.vim/bundle"
    state: directory
    mode: 0755
- name: Create the colors directory
  file:
    path: "{{ ansible_env.HOME }}/.vim/colors"
    state: directory
    mode: 0755
- name: "Install pathogen"
  get_url:
    url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload"
- name: Install the .vimrc to the user's home folder
  copy:
    src: vimrc
    dest: "{{ansible_env.HOME}}/.vimrc"
    mode: 0755
- name: "Install plugins"
  git:
    repo: "{{ item.repo }}"
    version: "{{ item.version | default('master') }}"
    dest: "/{{ ansible_env.HOME }}/.vim/bundle/{{ item.name | default(item.repo.split('/')[-1][:-4]) }}"
    depth: 1
  with_items:
  - repo: "https://github.com/tomasr/molokai.git"
    name: molokai ## default: vim-elixir
    version: master ## default: master
  - repo: "https://github.com/sickill/vim-monokai"
    name: vim-monokai ## default: vim-elixir
  - repo: "https://github.com/PProvost/vim-ps1.git"
    name: vim-ps1
  - repo: "https://github.com/rhysd/vim-llvm.git"
    name: vim-llvm
  - repo: "https://github.com/google/vim-jsonnet"
    name: vim-jsonnet
